services:
  - type: web
    name: waha-render
    env: docker
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: WAHA_API_KEY
        sync: false
      - key: WAHA_HMAC_SECRET
        sync: false
      - key: WHATSAPP_DEFAULT_ENGINE
        value: NOWEB
      - key: WAHA_WORKER_RESTART_SESSIONS
        value: "true"
      - key: WAHA_LOG_LEVEL
        value: info
